const mentors = [
  {
    gh_id: 17582916,
    preferred_name: 'Robbie Jaeger',
    preferred_contact: 'slack',
    bio: 'you will probably hear me coming before you ever actually see me',
    location: 'Denver, CO',
    avatar_url: 'https://avatars.githubusercontent.com/u/17582916?',
    slack: 'robbiejaeger',
    email: 'jaeger.rob@gmail.com',
    phone: '303-555-5555',
    accepting_new: 'y',
    availability: 'weekdays after 5, weekends',
    company: 'microsoft',
    position: 'senior dev',
    dev_type: 'backend',
    stack: 'Ruby/Rails, Python/Django, yelling, yodeling, loud noises',
    pairing_location: 'screenhero'
  },
  // {
  //   gh_id: 17582916,
  //   preferred_name: 'Robbie Jaeger',
  //   preferred_contact: 'slack',
  //   bio: 'you will probably hear me coming before you ever actually see me',
  //   location: 'Robbies house',
  //   avatar_url: 'https://avatars.githubusercontent.com/u/17582916?',
  //   slack: 'robbiejaeger',
  //   email: 'jaeger.rob@gmail.com',
  //   phone: '303-555-5555',
  //   accepting_new: 'y',
  //   availability: 'weekdays after 5, weekends',
  //   company: 'microsoft',
  //   position: 'senior dev',
  //   dev_type: 'backend',
  //   stack: 'Ruby/Rails, Python/Django, yelling, yodeling, loud noises',
  //   pairing_location: 'screenhero'
  // },
  {
    gh_id: 8650958,
    preferred_name: 'Yung Jhun',
    preferred_contact: 'slack',
    bio: 'suh dude, you can catch me salt baeing on my boosted board on the way to get burritos',
    location: 'wahoos fish tacos',
    avatar_url: 'https://avatars.githubusercontent.com/u/8650958?',
    slack: 'jhunbug',
    email: 'joshuajhun@gmail.com',
    phone: '303-550-5555',
    accepting_new: 'y',
    availability: 'weekdays after 5, weekends',
    company: 'SendGrid',
    position: 'senior dev',
    dev_type: 'front end',
    stack: 'Node.js, React',
    pairing_location: 'turing, screenhero'
  },
  {
    gh_id: 43102,
    preferred_name: 'Jeff Casimir',
    preferred_contact: 'slack',
    bio: 'I like to make people feel uncomfortable. Go to the guest speaker.  Also, I changed the entire plan just now at the last second and am going to wing it',
    location: 'wherever I feel like',
    avatar_url: 'https://avatars.githubusercontent.com/u/43102?',
    slack: 'j3',
    email: 'jeff@turing.io',
    phone: '718-555-5555',
    accepting_new: 'y',
    availability: 'weekdays after 5, weekends',
    company: 'turing',
    position: 'senior dev',
    dev_type: 'full stack',
    stack: 'Ruby/Rails, Python/Django, Node.js, React',
    pairing_location: 'turing, screenhero'
  }
  // {
  //   gh_id: 23202538,
  //   preferred_name: 'Spencer Hilvitz',
  //   preferred_contact: 'slack',
  //   bio: 'ridiculous',
  //   location: 'anywhere but the basement',
  //   avatar_url: 'https://avatars.githubusercontent.com/u/23202538?',
  //   slack: 'hilvitzs',
  //   email: 'spencer.hilvitz@gmail.com',
  //   phone: '718-555-5555',
  //   accepting_new: 'y',
  //   availability: 'weekdays after 5, weekends',
  //   company: 'turing',
  //   position: 'senior dev',
  //   dev_type: 'full stack',
  //   stack: 'Ruby/Rails, Python/Django, Node.js, React',
  //   pairing_location: 'turing, screenhero',
  //   id: 4
  // }
]

module.exports = mentors;
