const mentors = [
    {
        "timestamp": "2016-09-16T20:29:37.748Z",
        "name": "Adam K Jensen",
        "location": "Seattle, WA",
        "jobTitleEmployer": "Front End Engineer",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1508 Alumni. Worked at various startups doing customer relations. I started coding out of curiosity which led me to helping customers with their Wordpress blogs. Now I work with Modern Javascript, JS frameworks ( primarily React ), babel , Webpack, etc. Lots of Front-End stuffs.\n\nI currently live in Seattle, WA. I can possibly provide insight on the following topics: Front End tooling and languages, Remote work,  resume prep, job searching, networking remotely(not in Denver). \n\n",
        "technicalAreasOfExpertise": "Ruby/Rails, CS Fundamentals, Technical Interview Prep, node.js, React.js, Civic Tech, UI Development (Mockup --> Markup), CSS/Sass",
        "nontechnicalAreasOfExpertise": "Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack is preferred. I am @adamki\n",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2016-09-16T20:58:52.606Z",
        "name": "Adrienne Domingus",
        "location": "Seattle, WA",
        "jobTitleEmployer": "Software Engineer, Skilljar",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alum",
        "technicalAreasOfExpertise": "Ruby/Rails, Python/Django",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack, @adrienne",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2017-02-15T16:30:36.674Z",
        "name": "Al Scott",
        "location": "Denver, CO",
        "jobTitleEmployer": "Lead Developer, Campspot",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Software developer with lots of experience with startups and consulting. ",
        "technicalAreasOfExpertise": "Ruby/Rails, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, Angular, Ember, UI Development (Mockup --> Markup), CSS/Sass, Java, Testing, TDD, Architecture",
        "nontechnicalAreasOfExpertise": "Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack (al.scott)",
        "preferredPairingmeetingLocation": "In Person not at Turing",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime",
        "undefined": "Inactive on Slack"
    },
    {
        "timestamp": "2016-09-16T18:15:09.358Z",
        "name": "Alex Jensen",
        "location": "Colorado",
        "jobTitleEmployer": "Developer, DRH Internet",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "alumni",
        "technicalAreasOfExpertise": "Ruby/Rails, Functional Programming, CS Fundamentals, React.js, elixir",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack: @alexj",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "always open for questions. no particular schedule for pairing"
    },
    {
        "timestamp": "2016-09-17T12:48:06.238Z",
        "name": "Andrew Thal",
        "location": "Brooklyn, New York",
        "jobTitleEmployer": "Engineer IV, 2U",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Hungry Academy Alumnus, previously wrote software at LivingSocial and Bonobos. Turing mentor for ~2 years",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js, CSS/Sass, Python, Elixir",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @athal7 or email hello@athal7.com",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime"
    },
    {
        "timestamp": "2016-09-16T18:39:01.034Z",
        "name": "Andrew Watkins (Watts)",
        "location": "San Francisco",
        "jobTitleEmployer": "Software Developer, InfluxData",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni",
        "technicalAreasOfExpertise": "Go, Functional Programming, React.js",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Wellness & Stress Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack - @watts",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM"
    },
    {
        "timestamp": "2016-09-23T03:42:22.358Z",
        "name": "Andy Mention",
        "location": "Leadville, CO",
        "jobTitleEmployer": "Software Engineer, Brightcove",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1406 4 lyfe, also all the CO sporty things",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Functional Programming",
        "nontechnicalAreasOfExpertise": "Ruby/Rails, DevOps, Functional Programming, Docker, Elixir, Git, vim",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack: @andydangerous, amention@gmail.com, ",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts, vim/tmux :)",
        "generalAvailability": "Mon-Thurs after 5pm, or by appointment"
    },
    {
        "timestamp": "2016-12-02T17:41:15.332Z",
        "name": "Angela Lindow",
        "location": "Denver, CO ",
        "jobTitleEmployer": "Software Engineer, P2Binvestor",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumna, Parent, Previously worked for this company in an operations role, English major",
        "technicalAreasOfExpertise": "Ruby/Rails, CSS/Sass",
        "nontechnicalAreasOfExpertise": "Resume & Cover Letters, Culture/Behavioral Interview Prep, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @angela",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Available for questions via slack throughout the day"
    },
    {
        "timestamp": "2017-06-08T20:44:05.345Z",
        "name": "Bekah Lundy",
        "location": "Denver, CO",
        "jobTitleEmployer": "Full Stack Engineer",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I graduated from the 1610 Front End Program. I was a student in college before this and decided to pursue software development. I would love to talk to anyone!",
        "technicalAreasOfExpertise": "Technical Interview Prep, node.js, React.js, Angular, UI Development (Mockup --> Markup), CSS/Sass, JavaScript",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: @bekahlundy",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime"
    },
    {
        "timestamp": "2016-09-16T18:20:11.680Z",
        "name": "Brett Grigsby",
        "location": "Denver, CO",
        "jobTitleEmployer": "DagonIT",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alum in my first job",
        "technicalAreasOfExpertise": "Ruby/Rails, Functional Programming, Angular",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Wellness & Stress Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2017-04-10T17:44:49.956Z",
        "name": "Brett Nekolny",
        "location": "Denver, CO",
        "jobTitleEmployer": "Sr. Manager of Engineering, Under Armour Connected Fitness",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Love for leadership and growing people. Eager to fill any role in a group and organization. ",
        "technicalAreasOfExpertise": "Python, System Design",
        "nontechnicalAreasOfExpertise": "Project Management, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "SMS 630-202-0783; nekolny.brett@gmail.com",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-07-07T16:02:21.864Z",
        "name": "Brian Sayler",
        "location": "Chicago, IL",
        "jobTitleEmployer": "Software Developer, ThoughtWorks",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1603 Alum",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, CS Fundamentals, Technical Interview Prep, React.js, Python",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @saylerb",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime"
    },
    {
        "timestamp": "2016-09-23T15:24:16.963Z",
        "name": "Brian Winterling",
        "location": "Denver, CO",
        "jobTitleEmployer": "Sr. Software Developer, Muve Health",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "gschool[1] aka Turing 1309, mostly working on Rails APIs these days.  When I'm not hanging out with my family(two kids), you'll find me playing tennis, watching live music, or doing something outdoorsy",
        "technicalAreasOfExpertise": "Ruby/Rails/APIs, Technical Interviews",
        "nontechnicalAreasOfExpertise": "Project Management, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack or email is fine.",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays before 9am, weekdays after 4pm, random"
    },
    {
        "timestamp": "2016-09-20T17:10:53.810Z",
        "name": "Chelsea Johnson",
        "location": "Broomfield, CO",
        "jobTitleEmployer": "Web Developer, Points of Light",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "speech therapist",
        "technicalAreasOfExpertise": "Ruby/Rails, node.js, Ember, Civic Tech",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack, cheljoh",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-09-29T17:30:52.982Z",
        "name": "Chris Downard",
        "location": "Denver, CO",
        "jobTitleEmployer": "Engineering Manager, Granicus",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I love helping folks who are learning as I received a ton of help.",
        "technicalAreasOfExpertise": "Ruby/Rails, CS Fundamentals, Technical Interview Prep, React.js, Civic Tech, UI Development (Mockup --> Markup), CSS/Sass, Actual Javascript (tm), Soft skills, management, SDLC, Agile",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Zoom, Google Hangouts, Slack, whatever works",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, PM"
    },
    {
        "timestamp": "2016-09-16T19:58:42.466Z",
        "name": "Christopher Moeller",
        "location": "Milwaukee, WI",
        "jobTitleEmployer": "Software Developer, Chargify",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Self taught developer focused on Ruby on Rails and JS (mostly React at work)",
        "technicalAreasOfExpertise": "Ruby/Rails, Functional Programming, React.js",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Project Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack if it's urgent (@cmoel), email otherwise",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Some weekends at various times"
    },
    {
        "timestamp": "2017-07-13T17:01:07.743Z",
        "name": "Daniel Glauser",
        "location": "Denver, CO",
        "jobTitleEmployer": "Co-founder, Cambium Consulting",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I've been writing code for 20+ years and have worked across a wide swath of industries. I've served as a developer, architect, director, and co-founder. Mentoring and teaching bring me a lot of joy, and I love working with functional programming languages, especially Clojure. Recently I've co-founded a software consultancy. The majority of our client work is in Clojure and ClojureScript We are hoping to double down on that niche and continue to expand.",
        "technicalAreasOfExpertise": "Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep, Clojure and ClojureScript",
        "nontechnicalAreasOfExpertise": "Public Speaking, Speaking proposals, Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack, danielglauser",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays, PM"
    },
    {
        "timestamp": "2016-09-17T00:19:18.441Z",
        "name": "Danny Glunz",
        "location": "Denver",
        "jobTitleEmployer": "Software Engineer, Pana",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1409 alumni - double leo",
        "technicalAreasOfExpertise": "Ruby/Rails, Go, CS Fundamentals, node.js",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack -> @dglunz",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing",
        "generalAvailability": "Weekends, AM"
    },
    {
        "timestamp": "2017-07-01T02:16:08.904Z",
        "name": "Dan Olson",
        "location": "Denver, CO",
        "jobTitleEmployer": "Unemployed",
        "technicalAreasOfExpertise": "Ruby/Rails, Technical Interview Prep",
        "nontechnicalAreasOfExpertise": "Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: @dano",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekends, PM, 10:00 pm - 12:00 am"
    },
    {
        "timestamp": "2016-10-07T05:02:10.213Z",
        "name": "Dave Maurer",
        "location": "Aurora Colorado",
        "jobTitleEmployer": "Unemployed",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni",
        "technicalAreasOfExpertise": "Ruby/Rails, Javascript",
        "nontechnicalAreasOfExpertise": "Resume & Cover Letters, Culture/Behavioral Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: @dave.maurer",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing",
        "generalAvailability": "Weekdays, AM, Weekdays, after 5PM, Some weekends. Subject to me not having plans :)."
    },
    {
        "timestamp": "2016-09-22T13:10:44.381Z",
        "name": "David Whitaker",
        "location": "Denver",
        "jobTitleEmployer": "Web Developer, Points of Light",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Americorps alum, worked in organic/natural food industry prior to becoming a web dev.  ",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, React.js, Ember, UI Development (Mockup --> Markup), CSS/Sass",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Project Management, Resume & Cover Letters",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack",
        "preferredPairingmeetingLocation": "In Person at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime"
    },
    {
        "timestamp": "2017-07-06T17:53:38.675Z",
        "name": "Dylan Avery",
        "location": "Denver",
        "jobTitleEmployer": "Node Developer, IdeasByNature",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I love Rap music and I work in the Blockchain industry.",
        "technicalAreasOfExpertise": "Technical Interview Prep, node.js, React.js, UI Development (Mockup --> Markup), CSS/Sass, Blockchain",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2016-09-17T21:59:24.905Z",
        "name": "Emily Freeman",
        "location": "Denver, Colorado",
        "jobTitleEmployer": "Software Engineer, Wazee Digital",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I'm a Turing alumni (1508 BE) and graduated in March 2016. I have a 20-month old daughter, Clara, who is the light of my world and served as my inspiration to get through Turing. I'm originally from DC (with an 8-year layover in Florida) and am SUPER passionate about fitness — specifically powerlifting. Previously I worked in PR/Communications and as a ghostwriter. I also briefly worked in politics and non-profit fundraising. I blog when I can at emilydowdle.com. ",
        "technicalAreasOfExpertise": "Ruby/Rails, Java",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Wellness & Stress Management, Culture/Behavioral Interview Prep, Parenting, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: emilyfreeman",
        "preferredPairingmeetingLocation": "Grabbing lunch, coffee",
        "generalAvailability": "Weekdays,  Lunchtime"
    },
    {
        "timestamp": "2016-10-19T01:13:39.027Z",
        "name": "Emily Morehouse",
        "location": "Denver",
        "jobTitleEmployer": "Co-Founder/CTO, Cuttlesoft",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Studied Theatre, Criminology and Computer Science (and a little math and psychology for good measure). Avid OSS and CPython supporter/contributor. Recently moved to Denver, still settling my love affair with the mountains and acclimating to living above sea level. Yogi, dog lover, builder, thinker, coffee-drinker, face-maker.",
        "technicalAreasOfExpertise": "DevOps, CS Fundamentals, Technical Interview Prep, node.js, Angular, UI Development (Mockup --> Markup), CSS/Sass, Python/Flask, Ionic",
        "nontechnicalAreasOfExpertise": "Project Management, Resume & Cover Letters, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack (@emilym) but any method works (let's be real, they all go to my phone anyways)",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-09-18T20:22:07.495Z",
        "name": "Ernie Miller",
        "location": "Louisville, KY",
        "jobTitleEmployer": "Engineering Manager, CareZone",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Friend of Turing, occasional visitor (IT HAS BEEN TOO LONG), potential mentor.",
        "technicalAreasOfExpertise": "Ruby/Rails, Technical Interview Prep, React.js, Option 15",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Wellness & Stress Management, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "E-mail: ernie@ernie.io, also on Slack as @ernie and at 502-724-3082.",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-09-17T22:33:26.497Z",
        "name": "Glen Egbert",
        "location": "Salida, CO",
        "jobTitleEmployer": "Developer, HubTran",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni, Parent of 2, Working 100% remotely as a dev at HubTran since 2/2015",
        "technicalAreasOfExpertise": "Ruby/Rails, React.js",
        "nontechnicalAreasOfExpertise": "Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Email - glenegbert1@gmail.com",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-03-19T22:40:12.886Z",
        "name": "Gurusundesh Khalsa",
        "location": "Chicago, IL",
        "jobTitleEmployer": "Software Engineer, Allstate",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni. Very odd mix of things.",
        "technicalAreasOfExpertise": "Ruby/Rails, CS Fundamentals, React.js, Java",
        "nontechnicalAreasOfExpertise": "Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack @gurusundesh",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-01-30T23:11:32.371Z",
        "name": "Heidi Hoopes",
        "location": "Denver/Thorton",
        "jobTitleEmployer": "Application Developer, Aetna",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I'm an alumni who spent time after graduation providing student support at Turing. I'm a parent and formerly was employed as a biologist & tech journalist. I currently work purely on the backend of a Rails/Elixir app that has a different architecture than what you'll experience at Turing. ",
        "technicalAreasOfExpertise": "Ruby/Rails, Functional Programming, Elixir, AWS, integration testing",
        "nontechnicalAreasOfExpertise": "Technical Interview Prep, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "@heidi on Slack, heidih@gmail.com",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-06-27T23:31:02.414Z",
        "name": "Hilary Denton",
        "location": "Denver, CO",
        "jobTitleEmployer": "Muve Health",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni",
        "technicalAreasOfExpertise": "Functional Programming, React.js",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: hilaryous",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-02-08T17:11:14.102Z",
        "name": "Horace Williams",
        "location": "Los Angeles",
        "jobTitleEmployer": "Software Engineer, Factual",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Former Instructor",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Data Science, Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js, Civic Tech, Python, Clojure",
        "nontechnicalAreasOfExpertise": "Technical Interview Prep, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack (@horace)",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, PM"
    },
    {
        "timestamp": "2016-10-04T19:27:38.613Z",
        "name": "Horacio Chavez",
        "location": "Monterrey, Mexico",
        "jobTitleEmployer": "All & Simple Founder",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1406 Alumni",
        "technicalAreasOfExpertise": "Ruby/Rails, UI Development (Mockup --> Markup), CSS/Sass",
        "nontechnicalAreasOfExpertise": "Project Management, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @horacio",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts, Code Review via Github's PR",
        "generalAvailability": "Weekdays, after 7PM"
    },
    {
        "timestamp": "2016-09-16T18:13:35.462Z",
        "name": "Ian Douglas",
        "location": "Boulder, CO",
        "jobTitleEmployer": "Growth Hacker/DevRel, GetStream.io",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "20yr webdev experience, love to help with the career side of things like resume feedback and tech interview practice, or working through architecture problems and API development.",
        "technicalAreasOfExpertise": "DevOps, Go, CS Fundamentals, Technical Interview Prep",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @iandouglas, ian.douglas@iandouglas.com",
        "preferredPairingmeetingLocation": "Appear.in, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-09-17T03:22:39.415Z",
        "name": "Jack Yeh",
        "location": "Denver, CO",
        "jobTitleEmployer": "Welltok, Inc.,",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni 1507",
        "technicalAreasOfExpertise": "Ruby/Rails, React.js",
        "nontechnicalAreasOfExpertise": "Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Turing Slack - jackyeh",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-07-12T17:11:39.302Z",
        "name": "Jasmin Hudacsek",
        "location": "Denver, CO",
        "jobTitleEmployer": "Software Developer, OpHouse Solutions ",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I'm a 1606 backend alumni who has previous experience as a project manager and journalist. I also love craft beer and coffee, if you're into those things.",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, CS Fundamentals, React.js, UI Development (Mockup --> Markup), CSS/Sass, PHP",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack (@jazzy)",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-10-06T01:17:22.719Z",
        "name": "Jason Pilz",
        "location": "Anacortes, WA",
        "jobTitleEmployer": "Software Developer, Rumblefish",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1508 Alum, 3 daughters, work remote, love what I do",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack - username: jasonpilz",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-06-26T19:00:14.182Z",
        "name": "Jennifer Soden",
        "location": "Denver",
        "jobTitleEmployer": "QA Engineer, Aetna",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "While at Turing I ended up repeating two modules.",
        "technicalAreasOfExpertise": "Ruby/Rails, Testing; Minitest, RSpec, ability to figure things out together",
        "nontechnicalAreasOfExpertise": "Vent to me. Ask questions. Let's talk.",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "I check Slack regularly @MsJennyGiraffe. E-mail: jenniferlsoden@gmail.com, feel free to text me at 408 375 2138.",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Saturday PM"
    },
    {
        "timestamp": "2016-09-16T18:30:01.634Z",
        "name": "Jonah Moses",
        "location": "Portland",
        "jobTitleEmployer": "Software Engineer, New Relic",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni (gSchool[1]), Parent, Adventure Sports/Outdoors, ",
        "technicalAreasOfExpertise": "Ruby/Rails, React.js",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack, @jonah",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-09-27T15:13:09.243Z",
        "name": "Josh Ashton",
        "location": "Denver, CO",
        "jobTitleEmployer": "GutCheck",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "HR professional",
        "nontechnicalAreasOfExpertise": "Resume & Cover Letters, Culture/Behavioral Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "email - josh@gutcheckit.com",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing",
        "generalAvailability": "Weekdays, AM"
    },
    {
        "timestamp": "2016-12-08T22:48:44.095Z",
        "name": "Josh Cass",
        "location": "Lakewood, CO",
        "jobTitleEmployer": "Software Engineer, Bonusly",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni on my second job after Turing and soon-to-be parent",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, CSS/Sass",
        "nontechnicalAreasOfExpertise": "Project Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack: @joshcass or email: hello@joshcass.com",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
    },
    {
        "timestamp": "2017-03-17T17:52:27.711Z",
        "name": "Josh Washke",
        "location": "Littleton",
        "jobTitleEmployer": "Software Engineer, Consova Corporation",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1602 Alumni, former comp sci student. .Net and Angular 2 dev who develops desktop and web application in a windows environment",
        "technicalAreasOfExpertise": "CS Fundamentals, Angular, C#, .Net, SQL",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "@jwashke, jwashke@gmail.com, 9099106885 any of them works. ",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2016-10-11T03:17:16.052Z",
        "name": "July Tran",
        "location": "Denver, CO",
        "jobTitleEmployer": "GIS Developer, NREL",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1511 Alumni, background in public health and environmental policy",
        "technicalAreasOfExpertise": "Ruby/Rails, node.js, Ember, Civic Tech, UI Development (Mockup --> Markup), CSS/Sass",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Wellness & Stress Management, Project Management, Resume & Cover Letters, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: @july",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekends, PM"
    },
    {
        "timestamp": "2016-09-16T18:58:55.254Z",
        "name": "Justin Crawford",
        "location": "Boulder",
        "jobTitleEmployer": "Product Engineer, Mozilla",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Cofounder, dojo4. People/project/product manager. Parent.",
        "technicalAreasOfExpertise": "node.js, UI Development (Mockup --> Markup), Option 15, CSS/Sass",
        "nontechnicalAreasOfExpertise": "Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Parenting, Product development. Open source contribution. Marketing. Software process. Agency vs. Product Company vs. In-house jobs.",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "@hoosteeno on Slack",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime"
    },
    {
        "timestamp": "2016-09-16T19:04:37.125Z",
        "name": "Kaitlin Barrer",
        "location": "Denver",
        "jobTitleEmployer": "Software Engineer, CA Technologies",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I went to Davinci Coders, then worked for a startup, now work for CA.",
        "technicalAreasOfExpertise": "Ruby/Rails, Technical Interview Prep, React.js, Civic Tech, clojure",
        "nontechnicalAreasOfExpertise": "Resume & Cover Letters, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack or email (@kaitlinb or kaitlin.barrer@gmail.com)",
        "preferredPairingmeetingLocation": "In Person at Turing",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2016-09-16T22:12:13.390Z",
        "name": "Kurt Harriger",
        "location": "Denver, CO",
        "jobTitleEmployer": "CA Technologies",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Introduced to Turning via a co-worker and alumni Lovisa.  I have 20ish years experience.  I started programming in my teenage years.  I've worked with consulting firms, enterprises and startups.  I'm curious and passionate and always learning -- even now.",
        "technicalAreasOfExpertise": "DevOps, Data Science, Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Project Management, Resume & Cover Letters, Technical Interview Prep, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: kurtharriger",
        "preferredPairingmeetingLocation": "In Person at Turing",
        "generalAvailability": "Weekdays,  Lunchtime, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2017-06-30T17:19:42.618Z",
        "name": "Lovisa svallingson",
        "location": "Denver",
        "jobTitleEmployer": "Software Engineer, CA Technologies",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I'm a Turing alumna (1505) and worked as a TA at Turing for a few months before starting to work at CA technologies in Denver. I primarily write JavaScript at work but love diving in to new technologies/frameworks/languages. ",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Functional Programming, node.js, React.js",
        "nontechnicalAreasOfExpertise": "Public Speaking, Speaking proposals, Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
    },
    {
        "timestamp": "2016-09-29T16:10:52.548Z",
        "name": "Lydia Shafer",
        "location": "Denver",
        "jobTitleEmployer": "software developer, Wombat Security Technologies",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni",
        "technicalAreasOfExpertise": "Ruby/Rails, Ember, CSS/Sass",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack",
        "preferredPairingmeetingLocation": "any",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-07-17T19:16:04.081Z",
        "name": "Madison Kerndt",
        "location": "Boulder CO",
        "jobTitleEmployer": "IronCore Labs",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I am on a personal mission to help developers build secure software and to make the digital world a safer place for everyone. I am now Developer Evangelist and Software Engineer at IronCore Labs, before that I was a Techstars Associate, and a student at Turing (FE 1606). I have deep roots in the startup community and have a history of working with startups even before I became a front-end developer. I really enjoy building, creating, teaching, and contemplating the interplays between technology, community, privacy, and digital security. Reach out! \n\nLinkedIn: https://www.linkedin.com/in/mkerndt/\nTwitter: https://twitter.com/mkerndt\nEmail: madison.kerndt@ironcorelabs.com\nSlack: @madk",
        "technicalAreasOfExpertise": "Functional Programming, React.js, Ember, UI Development (Mockup --> Markup), CSS/Sass",
        "nontechnicalAreasOfExpertise": "Public Speaking, Speaking proposals, Wellness & Stress Management, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "email: madison.kerndt@ironcorelabs.com",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays, after 5PM, Before 8am or after 6pm"
    },
    {
        "timestamp": "2016-09-21T18:02:10.967Z",
        "name": "Marc Chung",
        "location": "San Francisco",
        "jobTitleEmployer": "Senior Software Engineer",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Previously at Lookout and ManCrates. Currently working at Handshake, a recruiting platform for University students.",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Technical Interview Prep",
        "nontechnicalAreasOfExpertise": "Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting, Social Issues in the Tech Industry",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekdays, after 5PM PST"
    },
    {
        "timestamp": "2017-03-30T17:07:26.603Z",
        "name": "Marina corona ",
        "location": "Denver ",
        "jobTitleEmployer": "Software engineer at GoSpotCheck",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "TFA alum, former educator, worked at CaptainU, love skiing. Backend rails developer ",
        "technicalAreasOfExpertise": "Ruby/Rails, Technical Interview Prep",
        "nontechnicalAreasOfExpertise": "Public Speaking, Speaking proposals, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack please @marinacor",
        "preferredPairingmeetingLocation": "In Person at Turing",
        "generalAvailability": "Weekdays: Lunchtime or after 5PM"
    },
    {
        "timestamp": "2016-11-23T01:49:33.288Z",
        "name": "Mark Miranda",
        "location": "Denver, CO",
        "jobTitleEmployer": "Software Developer, Headway.io",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni!",
        "technicalAreasOfExpertise": "Ruby/Rails, Functional Programming, React.js, Angular, UI Development (Mockup --> Markup), CSS/Sass",
        "nontechnicalAreasOfExpertise": "Project Management, Culture/Behavioral Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack - @mark",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2016-10-10T17:12:16.882Z",
        "name": "Marlo Major",
        "location": "Dallas",
        "jobTitleEmployer": "n/a",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni. Formerly at Active Network as Ruby dev. Scala enthusiast. JS not really my thing.",
        "technicalAreasOfExpertise": "Ruby/Rails, Functional Programming, CS Fundamentals, Scala",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @marlomajor",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-09-16T19:01:44.783Z",
        "name": "Matt Ewell",
        "location": "Salt Lake City, UT",
        "jobTitleEmployer": "RoR Developer, iCentris",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1507 Alumni, 15+ years in IT as systems engineer, solution architect, etc. before turning dev. Oh I went back to school and graduated with a CS degree in 2013. I enjoy bikram yoga, hiking and skiing.",
        "technicalAreasOfExpertise": "Ruby/Rails, CS Fundamentals, Technical Interview Prep, Civic Tech",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "matt.ewell@gmail.com, slack @plato721",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2017-03-28T16:53:45.795Z",
        "name": "Matt Kaufman",
        "location": "Denver, CO",
        "jobTitleEmployer": "Software Developer, Concept3D",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1608 Front End Alumni and former industrial robot programmer! I love digging into JS code and helping to solve problems, React is my area of focus/expertise currently. I have a passion for live music and outdoor activities, all the typical Colorado stuff. Just looking to spread the love, is all.",
        "technicalAreasOfExpertise": "CS Fundamentals, Technical Interview Prep, node.js, React.js, Civic Tech",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Jam Bands",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @mattk",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2016-09-16T19:01:47.875Z",
        "name": "Matt Rogers",
        "location": "Dallas, TX",
        "jobTitleEmployer": "Sr. Developer, Teladoc",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Traditional CS Degree. Dad to two girls.  Have worn the developer, team lead, and manager hats. Mentor since gSchool-1.",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, Technical Interview Prep",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Project Management, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack (@mattr), Email (codemattr@gmail.com)",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2016-10-08T22:46:02.563Z",
        "name": "Micah Adams",
        "location": "Denver, CO",
        "jobTitleEmployer": "Lead Engineer, Homebot",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "10 years of professional experience as a full stack/back end engineer. ",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Go, Data Science, Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Sack, email (micah.shawn.adams@gmail.com), SMS 817.507.7939",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
    },
    {
        "timestamp": "2016-09-17T11:22:37.762Z",
        "name": "Michael Siegfried",
        "location": "Santa Barbara, CA",
        "jobTitleEmployer": "Senior Engineer, Procore Technologies",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Probably birdwatching. I know of Turing through Mimi.",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Technical Interview Prep, Postgres",
        "nontechnicalAreasOfExpertise": "Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack (@siggy), sms (661.600.3784), email(siggymcfried@gmail.com)",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2017-03-17T17:49:06.516Z",
        "name": "Nicholas Dorans",
        "location": "Fort Collins",
        "jobTitleEmployer": "Semantic Technology Developer, Semantic Arts",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Turing Alumni 1511, 10 years experience in the HVAC Industry",
        "technicalAreasOfExpertise": "Ruby/Rails, Data Science, CS Fundamentals, node.js, React.js",
        "nontechnicalAreasOfExpertise": "Culture/Behavioral Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @nickynonaps",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Zoom, Google Hangouts, If you're willing to come to Fort Collins, I'll gladly meet with you.",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2017-07-12T16:54:47.687Z",
        "name": "Nicholas Martinez",
        "location": "Denver ",
        "jobTitleEmployer": "250OK",
        "technicalAreasOfExpertise": "Ruby/Rails, Python, UI Automation",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack or Email",
        "preferredPairingmeetingLocation": "In Person at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2017-06-30T17:59:17.917Z",
        "name": "Nick Chambers",
        "location": "Denver, CO",
        "jobTitleEmployer": "Software Engineer, Tendril",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Former outdoor industry PR professional with a deep, undying love of JavaScript.  ",
        "technicalAreasOfExpertise": "Technical Interview Prep, node.js, React.js, Civic Tech, CSS/Sass",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack ",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
    },
    {
        "timestamp": "2017-06-26T18:02:07.426Z",
        "name": "Nick Isaacs",
        "location": "Boulder, CO",
        "jobTitleEmployer": "Software Engineer, Twitter",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I am a mostly self taught developer who has spend time at companies small and large. I have worked on a variety of projects both front and backend. I have touched Rails apps, large scale backend JVM based apps, service oriented architectures, iOS and Android apps, machine learning pipelines, and everything in between. I also love mentoring with Turing :)",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Machine Learning, CS Fundamentals, Technical Interview Prep, JVM languages, functional programming",
        "nontechnicalAreasOfExpertise": "Public Speaking, Speaking proposals, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack, email, sms, phone, all is fine",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2017-06-29T04:48:58.981Z",
        "name": "Nick Weiland",
        "location": "Los Angeles",
        "jobTitleEmployer": "Head of Product, Airbo",
        "technicalAreasOfExpertise": "Ruby/Rails",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack (@weilandia)",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-06-26T18:40:37.344Z",
        "name": "Noah Berman",
        "location": "Amsterdam, The Netherlands",
        "jobTitleEmployer": "Backend Developer, WeTransfer",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I'm a Turing alumni with a particular interest in the intersection between technology and social justice. I'm originally a writer and filmmaker and now I work for WeTransfer in Amsterdam. As a programmer I'm interested in just about everything, but particularly: ways of using tech to tell stories, security, making coffee at the press of a button, and creating applications that scale really well. Oh, and everything else also.",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Technical Interview Prep, Civic Tech, Hardware stuff (Raspberry Pi), Image and other media processing",
        "nontechnicalAreasOfExpertise": "Public Speaking, Speaking proposals, Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Social Issues in the Tech Industry, Imposter Syndrome",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: @noah, email: noah@noahberman.org (I'm in the CEST time zone so don't be offended if I don't write back immediately! :) )",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays,  Lunchtime, We can figure something out - I'm 8 hours ahead of Denver time."
    },
    {
        "timestamp": "2016-09-16T19:42:09.007Z",
        "name": "Paul Grever",
        "location": "Denver, CO",
        "jobTitleEmployer": "Software Engineer, GetOutfitted",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "A Turing ALumni 1412. Worked as full stack with meteor, before that was Product Manager for DubLabs building mobile apps for colleges and k-12 schools.",
        "technicalAreasOfExpertise": "Ruby/Rails, node.js, UI Development (Mockup --> Markup), Meteor ",
        "nontechnicalAreasOfExpertise": "Project Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-02-14T20:50:18.997Z",
        "name": "Rich Shea",
        "location": "Denver",
        "jobTitleEmployer": "Software Developer, Wombat Security Technologies",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Turing Graduate, Math Teacher, Healthcare Recruiter, Inside Sales for Biotech/Pharmaceutical Industry",
        "technicalAreasOfExpertise": "Ruby/Rails, Ember, JavaScript",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack",
        "preferredPairingmeetingLocation": "In Person not at Turing, Screenhero, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime"
    },
    {
        "timestamp": "2016-09-22T16:59:55.891Z",
        "name": "Rick Rein",
        "location": "Denver, CO",
        "jobTitleEmployer": "CTO of Operation Code; Software Engineer at Akamai Technologies",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Started life as a *nix admin, mostly work on getting new products to market, former USMC",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Project Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack (rickr), email (rick@rudelinux.org)",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, AM"
    },
    {
        "timestamp": "2016-09-16T18:20:23.678Z",
        "name": "Robert Cornell",
        "location": "Denver",
        "jobTitleEmployer": "Lead Developer, Alkami",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Coding/Professional Background: \n1. Alumni-ish of 1502/3/6? \n\n2. 10 years project management experience (architectural lighting control systems / theatrical rigging systems) \n\n3. 3-years software product owner experience with stealth startup in Breckenridge, CO (Cofounder)\n\n4. 8-years Law Enforcement experience (yes I was literally a cop, police car, gun, vest, badge, whole nine-yards) Also directed recruitment and hiring programs as well as lead field training division.\n\n5. < 1 Year, Lead Developer at Alkami (Founder) 6 Clients ranging from healthcare to agriculture industry. \n\n6. I have also run a daycare and have 15 years of experience in musical theatre\n\nPersonal Background:\n1. Colorado Native (I remember when Colfax was a shithole no one went to)\n2. Two kids (17YO Son and 15 YO Daughter)\n3. Wife is from Central Asian and I'm learning Russian (She works in financial services in Philadelphia)\n4. I travel\n5. Love Doctor who (my first Doctor was Tom Baker #4)\n6. I'm an introvert and quiet and most people think I'm angry a lot of the time.  (https://www.youtube.com/watch?v=sGlTeRWTsGU and https://www.youtube.com/watch?annotation_id=annotation_732306207&feature=iv&src_vid=sGlTeRWTsGU&v=r99Bznk2QJA)",
        "technicalAreasOfExpertise": "Ruby/Rails, React.js, I learn quick",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Project Management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "robert@alkami.io",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, As scheduled dependent on my travel schedule"
    },
    {
        "timestamp": "2016-09-22T22:12:18.830Z",
        "name": "Robert Gu",
        "location": "Los Angeles",
        "jobTitleEmployer": "Crafter, 8th Light",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alum",
        "technicalAreasOfExpertise": "Ruby/Rails, node.js, CSS/Sass",
        "nontechnicalAreasOfExpertise": "Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-01-24T16:41:12.331Z",
        "name": "Robbie Lane",
        "location": "Denver",
        "jobTitleEmployer": "Developer - TRELORA",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1508 Alumni",
        "technicalAreasOfExpertise": "Ruby/Rails, node.js, React.js, UI Development (Mockup --> Markup), CSS/Sass",
        "nontechnicalAreasOfExpertise": "Project Management, Culture/Behavioral Interview Prep, Parenting, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "slack",
        "preferredPairingmeetingLocation": "In Person at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-09-16T18:31:33.913Z",
        "name": "Ross Kaffenberger",
        "location": "Washington, DC",
        "jobTitleEmployer": "Senior Software Engineer, Freelance",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I just became a dad so now I shovel code and diapers.",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js, Ember",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "email: rosskaff@gmail.com, slack: @rossta",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, AM, Weekdays, after 5PM"
    },
    {
        "timestamp": "2016-09-16T19:11:49.726Z",
        "name": "Ryan Tyer",
        "location": "Boulder",
        "jobTitleEmployer": "Director of Engineering, Cloudability",
        "technicalAreasOfExpertise": "DevOps, Go, Data Science, Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js",
        "nontechnicalAreasOfExpertise": "Public Speaking, CFPs, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Anything other than phone.  @rtyer / ryan.tyer@gmail.com /3037098877",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
    },
    {
        "timestamp": "2017-07-12T18:06:02.821Z",
        "name": "Ryan Workman",
        "location": "Denver, CO",
        "jobTitleEmployer": "Web Developer, Dish Network",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I spent five years producing local newscasts across the country before joining Turing and changing careers.\nI am an avid music fan and play bass guitar and drums on the side.",
        "technicalAreasOfExpertise": "Ruby/Rails, DevOps, node.js, Angular, CSS/Sass",
        "nontechnicalAreasOfExpertise": "Public Speaking, Speaking proposals, Project Management, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Email: rdavid1099@gmail.com\nText: 303 815 0866\nSlack",
        "preferredPairingmeetingLocation": "In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts, I'm cool with whatever",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM, Weekends, PM"
    },
    {
        "timestamp": "2016-09-28T02:41:48.305Z",
        "name": "Tae Kim",
        "location": "Iowa",
        "jobTitleEmployer": "Javascript Developer, Blacklight CMS",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I graduated from Iowa State University with a degree in Software Engineering. I moved out to Denver about 2 1/2 years ago and love it here! This is one of the happiest places in the world.\n\nI had a few jobs back in Iowa. One was very IT-related, one was at a large company developing in Java. Both jobs were ehhhh. When I came to Denver, I joined the consulting community... and boy was it awesome. I learned a ton in my craft, from modern development to managing a team. It was an amazing experience.\n\nNow, I work remotely for a small company called Blacklight CMS. We create and maintain thousands of sites for a niche health market. I'm creating a template engine for them to help automate a lot of that maintenance (think WIX, Squarespace, or Wordpress).\n\nOn the side, I helped start a startup called Zipskee - a social platform to connect locals with travelers. We are a self-driven group of individuals that love what we do.\n\nIn my free time, I love going to shows and playing LoL. For those casuals out there, LoL = League of Legends. I love coding / mentoring on the side, so if you have any questions feel free to ask!",
        "technicalAreasOfExpertise": "CS Fundamentals, Technical Interview Prep, node.js, React.js, CSS/Sass",
        "nontechnicalAreasOfExpertise": "Culture/Behavioral Interview Prep, Technical Interview Prep",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack: @taekimjr, Email: taekimjr@gmail.com, SMS: 5157204901",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, PM"
    },
    {
        "timestamp": "2016-10-16T00:49:49.878Z",
        "name": "Thom Schlereth",
        "location": "Denver CO",
        "jobTitleEmployer": "N/A",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Alumni",
        "technicalAreasOfExpertise": "Ruby/Rails, Civic Tech",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack -  @thomp",
        "preferredPairingmeetingLocation": "In Person at Turing",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-05-02T17:25:39.120Z",
        "name": "Tommasina Miller",
        "location": "Denver",
        "jobTitleEmployer": "Software Engineer, Granicus",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1605 alumna (last backend-only cohort); Pahlka for life!; you can often find me at Code for Denver; I love community and grass-roots activism",
        "technicalAreasOfExpertise": "Ruby/Rails, Civic Tech",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Resume & Cover Letters, Social Issues in the Tech Industry, Starting diversity groups at work",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack @tommasina",
        "preferredPairingmeetingLocation": "In Person at Turing, Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays, after 5PM, Weekends, PM"
    },
    {
        "timestamp": "2017-01-24T18:17:10.991Z",
        "name": "Torie Joy-Warren",
        "location": "Seattle, WA",
        "jobTitleEmployer": "Software Engineer, CareZone",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "1508 Alumni. Previously worked in economic research. ",
        "technicalAreasOfExpertise": "Ruby/Rails, Technical Interview Prep",
        "nontechnicalAreasOfExpertise": "Wellness & Stress Management, Technical Interview Prep, Social Issues in the Tech Industry",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack (@torie) or email ",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
    },
    {
        "timestamp": "2016-09-19T01:46:16.419Z",
        "name": "Troy Denkinger",
        "location": "Brooklyn, NY",
        "jobTitleEmployer": "VP Engineering, TuneCore, Inc.",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "I've been coding for over 20 years and have a lot of experience in the digital music industry. For the past 10 years or so I have been an engineering manager at various startups and established companies. ",
        "technicalAreasOfExpertise": "Ruby/Rails, Functional Programming, Technical Interview Prep",
        "nontechnicalAreasOfExpertise": "Project Management, Technical Interview Prep, Product management",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "Slack & email",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Weekdays,  Lunchtime, Weekdays, after 5PM"
    },
    {
        "timestamp": "2017-05-03T00:52:10.553Z",
        "name": "Ville-Matti Hakanpää",
        "location": "Raumna, Finland",
        "jobTitleEmployer": "Senior Software Developer",
        "briefBackgroundWhatWouldYouLikeStudentsToKnowAboutYouAlumniParentJobHistoryBirdWatching": "Over 15 years on the field. I live in Finland, have 4 kids and been programming my whole life. Fell in love with Javascript again after AngularJS appeared, now all my projects are build with React.\n\nI have relatively strong backgroun in PHP, but if I can, I do backend with Node. Been working with databases for a long time...and loving every minute of it.\n\nI do a lot...coach floorball for kids, build own projects...and sing! :)",
        "technicalAreasOfExpertise": "node.js, React.js, Angular, CSS/Sass",
        "nontechnicalAreasOfExpertise": "Project Management, Parenting",
        "preferredMethodOfContactSlackEmailSmsPleaseIncludeUsername": "villematti@dapper.fi",
        "preferredPairingmeetingLocation": "Screenhero, Zoom, Google Hangouts",
        "generalAvailability": "Timezone is GMT +2, and then Weekdays after 5pm and weekends"
    }
]